// items type
export const LOAD_ITEMS = 'LOAD_ITEMS';
export const LOAD_ITEMS_SUCCESS = 'LOAD_ITEMS_SUCCESS';
export const LOAD_ITEMS_ERROR = 'LOAD_ITEMS_ERROR';
export const LOAD_PAGE = 'LOAD_PAGE';
export const LOAD_PAGE_SUCCESS = 'LOAD_PAGE_SUCCESS';
export const LOAD_PAGE_ERROR = 'LOAD_PAGE_ERROR';
export const ADD_ITEM = 'ADD_ITEM';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_ERROR = 'ADD_ITEM_ERROR';
export const EDIT_ITEM = 'EDIT_ITEM';
export const EDIT_ITEM_SUCCESS = 'EDIT_ITEM_SUCCESS';
export const EDIT_ITEM_ERROR = 'EDIT_ITEM_ERROR';
export const GET_EDIT_ITEM = 'GET_EDIT_ITEM';
export const GET_EDIT_ITEM_SUCCESS = 'GET_EDIT_ITEM_SUCCESS';
export const GET_EDIT_ITEM_ERROR = 'GET_EDIT_ITEM_ERROR';
export const GET_DELETE_ITEM = 'GET_DELETE_ITEM';
export const GET_DELETE_ITEM_SUCCESS = 'GET_DELETE_ITEM_SUCCESS';
export const GET_DELETE_ITEM_ERROR = 'GET_DELETE_ITEM_ERROR';
export const DELETE_ITEM = 'DELETE_ITEM';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_ERROR = 'DELETE_ITEM_ERROR';

//users type
export const CHECK_USER = 'CHECK_USER';
export const CHECK_USER_SUCCESS = 'CHECK_USER_SUCCESS';
export const CHECK_USER_ERROR = 'CHECK_USER_ERROR';